wallets = [
        {"coin": "XRP", "address": "rEb8TK3gBgk5auZkwc6sHnwrGVJH8DuaLh", "exchange": "Binance"},
        {"coin": "XRP", "address": "rEeEWeP88cpKUddKk37B2EZeiHBGiBXY3", "exchange": "Binance"},
        {"coin": "XRP", "address": "rs8ZPbYqgecRcDzQpJYAMhSxSi5htsjnza", "exchange": "Binance"},
        {"coin": "XRP", "address": "rPyCQm8E5j78PDbrfKF24fRC7qUAk1kDMZ", "exchange": "Bithump"},
        {"coin": "XRP", "address": "rsXT3AQqhHDusFs3nQQuwcA1yXRLZJAXKw", "exchange": "Uphold"},
        {"coin": "XRP", "address": "rMQ98K56yXJbDGv49ZSmW51sLn94Xe1mu1", "exchange": "Ripple"},
        {"coin": "XRP", "address": "rKveEyR1SrkWbJX214xcfH43ZsoGMb3PEv", "exchange": "Ripple"},
        {"coin": "XRP", "address": "rDxJNbV23mu9xsWoQHoBqZQvc77YcbJXwb", "exchange": "Upbit"},
        {"coin": "XRP", "address": "rw7m3CtVHwGSdhFjV4MyJozmZJv3DYQnsA", "exchange": "Bitbank"},
        {"coin": "XRP", "address": "r99QSej32nAcjQAri65vE5ZXjw6xpUQ2Eh", "exchange": "Coincheck"},
        {"coin": "XRP", "address": "rPJ5GFpyDLv7gqeB1uZVUBwDwi41kaXN5A", "exchange": "Binance"},
        {"coin": "XRP", "address": "rPz2qA93PeRCyHyFCqyNggnyycJR1N4iNf", "exchange": "Binance"},
        {"coin": "XRP", "address": "rNxp4h8apvRis6mJf9Sh8C6iRxfrDWN7AV", "exchange": "Binance"},
        {"coin": "XRP", "address": "rLNaPoKeeBjZe2qs6x52yVPZpZ8td4dc6w", "exchange": "Coinbase"},
        {"coin": "XRP", "address": "rRmgo6NW1W7GHjC5qEpcpQnq8NE74ZS1P", "exchange": "Coinbase"},
        {"coin": "XRP", "address": "rHrHuQM3E114yMyPjeULWfQmbwVBrHsBEy", "exchange": "Coinbase"},
        {"coin": "XRP", "address": "rLBunuhuRY7aUCnDkSQhaf5ewCvdcWUYjR", "exchange": "Coinbase"},
        {"coin": "XRP", "address": "rDw1Z5BqJejpKCGfncHJ9rwRq2kYLo4sJG", "exchange": "Coinbase"},
        {"coin": "XRP", "address": "rUfghnh1VAWajpAmxgrzLPiCXJ7RwdJUgt", "exchange": "Coinbase"},
        {"coin": "XRP", "address": "r3YsZdkznVzYBv141qhwXHDWoPUXLdksNw", "exchange": "Coinbase"},
        {"coin": "XRP", "address": "rUW9toSjQkLY6EspdnBJP2paG4hWKmNbMh", "exchange": "Kucoin"},
        {"coin": "XRP", "address": "rsf5FAyMDnTiA5Rm63xvEKnSy5MxHUnZvA", "exchange": "Kucoin"},
        {"coin": "XRP", "address": "r4pxv9txfQTyVkQUetNmyJqDy7s5fPPVfB", "exchange": "Kucoin"},
        {"coin": "XRP", "address": "rhKrvXY8zRvVyDLT4nfXB86HyhqQyvcr4c", "exchange": "Kucoin"},
        {"coin": "XRP", "address": "rBWFDgD785LUBDDgcCi9dAW6TH2Gmtq8CM", "exchange": "Kucoin"},
        {"coin": "XRP", "address": "rNFugeoj3ZN8Wv6xhuLegUBBPXKCyWLRkB", "exchange": "Kucoin"},
        {"coin": "XRP", "address": "rEW8BjpMyFZfGMjqbykbhpnr4KEb2qr6PC", "exchange": "Kucoin"},
        {"coin": "XRP", "address": "rBxszqhQkhPALtkSpGuVeqR6hNtZ8xTH3T", "exchange": "Kucoin"},
        {"coin": "XRP", "address": "rp4gqz1XdqMsWRZbzPdPAQWw1tg5LuwUVP", "exchange": "Kucoin"},
        {"coin": "XRP", "address": "rNEHKuQSB8FGt42NGckRSnq7XCAmJryX4h", "exchange": "Kucoin"},
        {"coin": "XRP", "address": "rsbfd5ZYWqy6XXf6hndPbRjDAzfmWc1CeQ", "exchange": "Luno"},        
        {"coin": "XRP", "address": "rLHzPsX6oXkzU2qL12kHCH8G8cnZv1rBJh", "exchange": "Kraken"},
        {"coin": "XRP", "address": "rUeDDFNp2q7Ymvyv75hFGC8DAcygVyJbNF", "exchange": "Kraken"},
        {"coin": "XRP", "address": "rGZjPjMkfhAqmc1ssEiT753uAgyftHRo2m", "exchange": "Kraken"},
        {"coin": "XRP", "address": "rp7TCczQuQo61dUo1oAgwdpRxLrA8vDaNV", "exchange": "Kraken"},
        {"coin": "XRP", "address": "rwnYLUsoBQX3ECa1A5bSKLdbPoHKnqf63J", "exchange": "CoinBase"},    
        {"coin": "XRP", "address": "rw2ciyaNshpHe7bCHo4bRWq6pqqynnWKQg", "exchange": "CoinBase"},
        {"coin": "XRP", "address": "rDAE53VfMvftPB4ogpWGWvzkQxfht6JPxr", "exchange": "Binance"},
        {"coin": "XRP", "address": "rNU4eAowPuixS5ZCWaRL72UUeKgxcKExpK", "exchange": "Binance"},
        {"coin": "XRP", "address": "rBtttd61FExHC68vsZ8dqmS3DfjFEceA1A", "exchange": "Binance"},
        {"coin": "XRP", "address": "rwpTh9DDa52XkM9nTKp2QrJuCGV5d1mQVP", "exchange": "CoinBase"},        
        {"coin": "BTC", "address": "34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo", "exchange": "Binance Cold Wallet"},
        {"coin": "BTC", "address": "bc1ql49ydapnjafl5t2cp9zqpjwe6pdgmxy98859v2", "exchange": "Robinhood Cold Wallet"},
        {"coin": "BTC", "address": "3M219KR5vEneNb47ewrPfWyb5jQ2DjxRP6", "exchange": "Binance Cold Wallet"},
        {"coin": "BTC", "address": "bc1qgdjqv0av3q56jvd82tkdjpy7gdp9ut8tlqmgrpmv24sq90ecnvqqjwvw97", "exchange": "Bitfinex Cold Wallet"},
        {"coin": "ETH", "address": "0xbe0eb53f46cd790cd13851d5eff43d12404d33e8", "exchange": "Binance"},
        {"coin": "ETH", "address": "0x742d35cc6634c0532925a3b844bc454e4438f44e", "exchange": "Bitfinex"},
        {"coin": "ETH", "address": "0x47ac0fb4f2d84898e4d9e7b4dab3c24507a6d503", "exchange": "Binance"},
        {"coin": "BTC", "address": "0x61edcdf5bb737adffe5043706e7c5bb1f1a56eea", "exchange": "Gemini"},
        {"coin": "BTC", "address": "0x28c6c06298d514db089934071355e5743bf21d60", "exchange": "Binance"},
        {"coin": "BTC", "address": "0xc61b9bb3a7a0767e3179713f3a5c7a9aedce193c", "exchange": "Bitfinex"}
        
    ]
